image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Python project with dependencies
    # Do not use `python -m pip install` with pyenv,
    # see https://github.com/pyenv/pyenv/issues/2243
    init: |
      pip install -r requirements.txt
